version: '3.8'

services:
  up_or_down:
    container_name: up_or_down-dev
    image: gwamaka/up_or_down:nightly2
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
      - "3307:3306"

